include Makefile.inc

KERNEL=kernel.bin

# Memory manager selection (default: K&R free-list)
# Usage: make MM_IMPL=buddy   -> use ./memory/memory_buddy.c
#        make MM_IMPL=kr      -> use ./memory/memory_manager.c (default)
MM_IMPL ?= kr
ifeq ($(MM_IMPL),buddy)
MM_SOURCE=./memory/memory_buddy.c
else
MM_SOURCE=./memory/memory_manager.c
endif

SOURCES=$(wildcard *.c ./drivers/*.c ./idt/*.c ./lib/*.c ./processes/*.c ./pipes/*.c ./semaphore/*.c) $(MM_SOURCE)
SOURCES_ASM=$(wildcard asm/*.asm)
HOT_OBJECTS=./drivers/video.o fonts.o # Compiled with -O3
OBJECTS=$(SOURCES:.c=.o)
OBJECTS_ASM=$(SOURCES_ASM:.asm=.o)
LOADERSRC=loader.asm

LOADEROBJECT=$(LOADERSRC:.asm=.o)
STATICLIBS=

all: $(KERNEL)

$(KERNEL): $(LOADEROBJECT) $(OBJECTS) $(STATICLIBS) $(OBJECTS_ASM)
	$(LD) $(LDFLAGS) -T kernel.ld -o $(KERNEL) $(LOADEROBJECT) $(OBJECTS) $(OBJECTS_ASM) $(STATICLIBS)

$(HOT_OBJECTS) : %.o: %.c
	$(GCC) -O3 $(GCCFLAGS) -I./include -c $< -o $@

$(filter-out $(HOT_OBJECTS),$(OBJECTS)) : %.o: %.c
	$(GCC) $(GCCFLAGS) -I./include -I./font_assets -c $< -o $@

%.o : %.asm
	$(ASM) $(ASMFLAGS) $< -o $@

# font.o:
# 	objcopy -O elf64-x86-64 -B i386 -I binary ./font_assets/Solarize.12x29.psf font.o

$(LOADEROBJECT):
	$(ASM) $(ASMFLAGS) $(LOADERSRC) -o $(LOADEROBJECT)

clean:
	rm -rf */*.o *.o *.bin

.PHONY: all clean
